on: 
  push: 
    branchs:
      - main

name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my_app

    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    # 8
    - name: Get latest code
      uses: actions/checkout@v3
    - name: Get latest java
      uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.3.3"
        channel: 'stable'
    



    - name: Get pwd
      run: pwd
    
  #  - name: change
  #    run: cd my_app

  #  - name: Get pwd2
  #    run: pwd
    
    # 12
    
    - name: Get dependencies
      run: flutter pub get

    # Runs a set of commands using the runners shell
    - name: Start release build
      run: flutter build web





    # HTTP Server Action - para teste de pagina
    # https://github.com/marketplace/actions/http-server-action

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.ftp_server }} 
        username: ${{ secrets.ftp_user }} 
        password: ${{ secrets.ftp_password }}  
        server-dir: public_html/site/flutter/
        local-dir: ./my_app/build/web/