on: 
  push: 
    branchs:
      - main

name: Deploy website on push
jobs:
  windows-deploy:
    name: WinDeploy
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./my_app
    steps:    
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
           channel: 'beta'
      - run: flutter --version
      - name: Get pwd
        run: pwd      
      - name: Get dependencies
        run: flutter pub get
      
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      # Collect the file and upload as artifact         
      - name: collect ipa artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-ipa
          # Path to the release files
          path: build/*.*

   

 

  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my_app

    steps:
#    - name: Get latest code
#      uses: actions/checkout@v2
    # 8
#    - name: Get latest code
    - uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
        

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.3.3"
        channel: 'stable'
        cache: true // 2


    - name: Get pwd
      run: pwd
    
  #  - name: change
  #    run: cd my_app

  #  - name: Get pwd2
  #    run: pwd
    
    # 12
    
    - name: Get dependencies
      run: flutter pub get

    - name: Get Teste
      run: flutter test

    # Runs a set of commands using the runners shell
    - name: Start release build
      run: flutter build web --base-href /${{ secrets.url_path }}/
  



    # HTTP Server Action - para teste de pagina
    # https://github.com/marketplace/actions/http-server-action

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.ftp_server }} 
        username: ${{ secrets.ftp_user }} 
        password: ${{ secrets.ftp_password }}  
        server-dir: public_html/site/flutter/
        local-dir: ./my_app/build/web/
