on: 
  push: 
    branchs:
      - main

name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    steps:
      uses: actions/checkout@v3
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web

    # HTTP Server Action - para teste de pagina
    # https://github.com/marketplace/actions/http-server-action

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.ftp_server }} 
        username: ${{ secrets.ftp_user }} 
        password: ${{ secrets.ftp_password }}  
        server-dir: public_html/site/flutter/
        local-dir: ./my_app/build/web/